"use client";
import { useRef, useState } from "react";
import { Download, ImagePlus, LoaderCircle, LogIn, Sparkles, Trash2, ChevronLeft, ChevronRight } from "lucide-react";
import { toPng } from "html-to-image";
import { supabase } from "@/lib/supabase";
type Card={id:string;title:string;body:string;visual:string;image:string;design:{accent:string;align:"left"|"center";overlay:number}};
const formats=[{id:"portrait",name:"세로 4:5",ratio:"4 / 5"},{id:"square",name:"정사각형 1:1",ratio:"1 / 1"},{id:"landscape",name:"가로 16:9",ratio:"16 / 9"}];
export default function Studio(){
 const [persona,setPersona]=useState("따뜻하고 감각적인 라이프스타일 큐레이터"),[topic,setTopic]=useState(""),[count,setCount]=useState(5),[format,setFormat]=useState("portrait"),[useCharacter,setUseCharacter]=useState(false),[reference,setReference]=useState(""),[cards,setCards]=useState<Card[]>([]),[sheet,setSheet]=useState(""),[active,setActive]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(""),[projectId,setProjectId]=useState<string>();
 const cardRef=useRef<HTMLDivElement>(null),card=cards[active],ratio=formats.find(x=>x.id===format)?.ratio||"4 / 5";
 const onUpload=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>setReference(String(reader.result));reader.readAsDataURL(file)};
 async function generate(){if(!topic.trim()){setError("카드뉴스 주제를 입력해 주세요.");return}setBusy(true);setError("");try{const res=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({persona,topic,count,format,referenceImage:useCharacter?reference:undefined,makeCharacterSheet:useCharacter})}),data=await res.json();if(!res.ok)throw new Error(data.error);setCards(data.cards);setSheet(data.characterSheet||"");setActive(0)}catch(e){setError(e instanceof Error?e.message:"생성하지 못했습니다.")}finally{setBusy(false)}}
 function update(key:"title"|"body",value:string){setCards(cs=>cs.map((c,i)=>i===active?{...c,[key]:value}:c))}
 async function regenerateImage(){if(!card)return;setBusy(true);setError("");try{const res=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({persona,topic,format,referenceImage:sheet||reference,card})}),data=await res.json();if(!res.ok)throw new Error(data.error);setCards(cs=>cs.map((c,i)=>i===active?{...c,image:data.image}:c))}catch(e){setError(e instanceof Error?e.message:"이미지를 다시 만들지 못했습니다.")}finally{setBusy(false)}}
 function move(dir:-1|1){const next=active+dir;if(next<0||next>=cards.length)return;const copy=[...cards];[copy[active],copy[next]]=[copy[next],copy[active]];setCards(copy);setActive(next)}
 async function download(){if(!cardRef.current||!card)return;const png=await toPng(cardRef.current,{pixelRatio:2,cacheBust:true}),link=document.createElement("a");link.download=`${active+1}-${card.title}.png`;link.href=png;link.click()}
 async function save(){if(!supabase){setError("Supabase 환경 변수를 먼저 설정해 주세요.");return}const {data:{user}}=await supabase.auth.getUser();if(!user){await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:location.href}});return}const payload={title:topic,persona,topic,settings:{count,format,useCharacter},cards,character_sheet:sheet||null,user_id:user.id},q=projectId?supabase.from("projects").update(payload).eq("id",projectId).select().single():supabase.from("projects").insert(payload).select().single(),{data,error}=await q;if(error)setError(error.message);else setProjectId(data.id)}
 return <main>
  <aside className="sidebar"><div className="logo"><Sparkles size={20}/> muse<span>cards</span></div><p className="eyebrow">AI CARD STUDIO</p><h1>당신의 이야기를<br/><i>한 장씩</i> 전하세요.</h1><p className="sidecopy">브랜드의 결을 담아, 완성도 높은 카드뉴스를 만듭니다.</p><div className="sidefoot">이미지는 <b>gpt-image-2</b>로 생성되며<br/>텍스트는 웹에서 선명하게 합성됩니다.</div></aside>
  <section className="composer"><header><div><p className="eyebrow">NEW PROJECT</p><h2>무엇을 만들까요?</h2></div><button className="ghost" onClick={save}><LogIn size={16}/> 로그인 · 저장</button></header><div className="form">
   <label>브랜드 페르소나<textarea value={persona} onChange={e=>setPersona(e.target.value)} rows={2}/></label><label>카드뉴스 주제<textarea placeholder="예: 바쁜 직장인을 위한 아침 루틴 5가지" value={topic} onChange={e=>setTopic(e.target.value)} rows={3}/></label>
   <div className="fieldrow"><label>카드 수<div className="stepper"><button onClick={()=>setCount(Math.max(2,count-1))}>−</button><b>{count}장</b><button onClick={()=>setCount(Math.min(10,count+1))}>+</button></div></label><label>이미지 비율<div className="segmented">{formats.map(f=><button key={f.id} className={format===f.id?"selected":""} onClick={()=>setFormat(f.id)}>{f.name}</button>)}</div></label></div>
   <div className="character"><div><b>나의 캐릭터 사용</b><span>사진이나 캐릭터를 기준으로 일관된 캐릭터 시트를 먼저 만듭니다.</span></div><button className={useCharacter?"toggle on":"toggle"} onClick={()=>setUseCharacter(!useCharacter)}><i/></button></div>
   {useCharacter&&<label className="upload">{reference?<img src={reference} alt="업로드한 캐릭터"/>:<ImagePlus size={24}/>}<span>{reference?"사진 바꾸기":"사진 또는 캐릭터 업로드"}<small>PNG, JPG · 얼굴이 잘 보이는 이미지</small></span><input type="file" accept="image/*" onChange={e=>onUpload(e.target.files?.[0])}/></label>}{error&&<p className="error">{error}</p>}<button className="generate" onClick={generate} disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Sparkles/>}{busy?"글과 이미지를 만들고 있어요…":"카드뉴스 만들기"}</button></div>{sheet&&<div className="sheet"><img src={sheet} alt="생성된 캐릭터 시트"/><span>일관성 기준 캐릭터 시트</span></div>}</section>
  <section className="workspace">{!cards.length?<div className="empty"><Sparkles/><h2>캔버스가 비어 있어요</h2><p>주제와 브랜드 페르소나를 입력하면<br/>글과 텍스트 없는 이미지를 함께 생성합니다.</p></div>:<><div className="toolbar"><span>{active+1} / {cards.length}</span><div><button onClick={()=>move(-1)} disabled={active===0}><ChevronLeft/></button><button onClick={()=>move(1)} disabled={active===cards.length-1}><ChevronRight/></button><button className="download" onClick={download}><Download size={16}/> PNG 저장</button></div></div><div className="canvaswrap"><div ref={cardRef} className="card" style={{aspectRatio:ratio}}><img src={card.image} alt="카드 이미지"/><div className="shade" style={{background:`linear-gradient(180deg, rgba(0,0,0,${card.design.overlay}) 0%, rgba(0,0,0,.75) 100%)`}}/><div className={`copy ${card.design.align}`}><span style={{background:card.design.accent}}>MUSE CARDS · {String(active+1).padStart(2,"0")}</span><h3>{card.title}</h3><p>{card.body}</p></div></div></div><div className="editor"><div className="thumbnails">{cards.map((x,i)=><button key={x.id} className={active===i?"active":""} onClick={()=>setActive(i)}><img src={x.image} alt=""/><span>{i+1}</span></button>)}</div><div className="editfields"><label>제목<input value={card.title} onChange={e=>update("title",e.target.value)}/></label><label>본문<textarea value={card.body} onChange={e=>update("body",e.target.value)}/></label><label>강조색<input type="color" value={card.design.accent} onChange={e=>setCards(cs=>cs.map((c,i)=>i===active?{...c,design:{...c.design,accent:e.target.value}}:c))}/></label><button className="outline" onClick={regenerateImage} disabled={busy}><ImagePlus size={16}/> 이미지 재생성</button><button className="outline" onClick={()=>setCards(cs=>cs.filter((_,i)=>i!==active))}><Trash2 size={16}/> 이 카드 삭제</button></div></div></>}</section>
 </main>
}
